<script>
// Single source of truth for your site
const DATA = {
  updatedAt: new Date().toISOString(),

  // ----------------- JOBS (20) -----------------
  jobs: [
    { id:"job-ssc-cgl-2025", title:"SSC CGL 2025 Apply Online", org:"SSC", tag:"New",
      start:"2025-08-01", last:"2025-08-30", fee:"UR/OBC: ₹100 • SC/ST/Female: ₹0", age:"18-32 (as per post)", qual:"Graduate",
      post:"Various Group B & C", vacancy:"TBA", status:"Application Open",
      notif_url:"https://ssc.nic.in/whatsnew/Document", apply_url:"https://ssc.nic.in/",
      website:"https://ssc.nic.in" },

    { id:"job-ssc-chsl-2025", title:"SSC CHSL 2025 Online Form", org:"SSC",
      start:"2025-07-20", last:"2025-08-20", fee:"UR/OBC: ₹100 • Others: ₹0", age:"18-27", qual:"12th Pass",
      post:"LDC/DEO/PA/SA", vacancy:"TBA",
      notif_url:"https://ssc.nic.in/whatsnew/Document", apply_url:"https://ssc.nic.in/",
      website:"https://ssc.nic.in" },

    { id:"job-ssc-gd-2025", title:"SSC GD Constable 2025 Online Form", org:"SSC",
      start:"2025-11-01", last:"2025-11-30", fee:"UR/OBC: ₹100 • Others: ₹0", age:"18-23", qual:"10th Pass",
      post:"GD Constable", vacancy:"TBA",
      notif_url:"https://ssc.nic.in/whatsnew/Document", apply_url:"https://ssc.nic.in/",
      website:"https://ssc.nic.in" },

    { id:"job-upsc-capf-2025", title:"UPSC CAPF (AC) 2025", org:"UPSC",
      start:"2025-04-XX", last:"2025-05-XX", fee:"UR: ₹200 • Female/SC/ST: ₹0", age:"20-25", qual:"Graduate",
      post:"Assistant Commandant", vacancy:"TBA",
      notif_url:"https://upsc.gov.in", apply_url:"https://upsconline.nic.in",
      website:"https://upsc.gov.in" },

    { id:"job-upsc-ese-2026", title:"UPSC ESE 2026 (Pre) Notification", org:"UPSC",
      start:"2025-09-XX", last:"2025-10-XX", fee:"UR: ₹200 • Female/SC/ST: ₹0", age:"21-30", qual:"Engineering Degree",
      post:"Group A Services", vacancy:"TBA",
      notif_url:"https://upsc.gov.in", apply_url:"https://upsconline.nic.in",
      website:"https://upsc.gov.in" },

    { id:"job-nta-ugcnet-dec", title:"UGC NET December Session", org:"NTA",
      start:"2025-09-XX", last:"2025-10-XX", fee:"UR: ₹1150 • EWS/OBC: ₹600 • SC/ST: ₹325", qual:"PG",
      post:"Assistant Professor/JRF", vacancy:"—",
      notif_url:"https://ugcnet.nta.nic.in", apply_url:"https://ugcnet.nta.nic.in",
      website:"https://nta.ac.in" },

    { id:"job-rrb-alp-2025", title:"Railway RRB ALP 2025", org:"Railway Recruitment Boards",
      start:"2025-12-XX", last:"2026-01-XX", fee:"UR/OBC: ₹500 (partial refund) • SC/ST/Female: ₹250", age:"18-30", qual:"10+2/ITI/Diploma",
      post:"Assistant Loco Pilot", vacancy:"TBA",
      notif_url:"http://www.rrbcdg.gov.in/", apply_url:"http://www.rrbcdg.gov.in/",
      website:"https://indianrailways.gov.in" },

    { id:"job-rrb-technician-2025", title:"RRB Technician 2025", org:"Railway Recruitment Boards",
      start:"2025-09-XX", last:"2025-10-XX", fee:"UR/OBC: ₹500 • Others: ₹250", age:"18-33", qual:"ITI/Diploma",
      post:"Technician Grade", vacancy:"TBA",
      notif_url:"http://www.rrbcdg.gov.in/", apply_url:"http://www.rrbcdg.gov.in/",
      website:"https://indianrailways.gov.in" },

    { id:"job-upsssc-2025-vdo", title:"UPSSSC VDO 2025 Re-Notification", org:"UPSSSC",
      start:"2025-08-05", last:"2025-08-25", fee:"As per rules", age:"18-40", qual:"12th + CCC",
      post:"Gram Panchayat Adhikari", vacancy:"TBA",
      notif_url:"http://upsssc.gov.in", apply_url:"http://upsssc.gov.in",
      website:"http://upsssc.gov.in" },

    { id:"job-delhi-police-constable-2025", title:"Delhi Police Constable 2025", org:"Delhi Police/SSC",
      start:"2025-09-XX", last:"2025-10-XX", fee:"UR/OBC: ₹100 • Others: ₹0", age:"18-25", qual:"12th",
      post:"Constable (Exe.)", vacancy:"TBA",
      notif_url:"https://delhipolice.gov.in", apply_url:"https://ssc.nic.in/",
      website:"https://delhipolice.gov.in" },

    { id:"job-ibps-po-2025", title:"IBPS PO 2025", org:"IBPS",
      start:"2025-07-XX", last:"2025-08-XX", fee:"UR/OBC: ₹850 • SC/ST/PwBD: ₹175", qual:"Graduate",
      post:"Probationary Officer", vacancy:"TBA",
      notif_url:"https://www.ibps.in", apply_url:"https://www.ibps.in",
      website:"https://www.ibps.in" },

    { id:"job-ibps-clerk-2025", title:"IBPS Clerk 2025", org:"IBPS",
      start:"2025-07-XX", last:"2025-08-XX", fee:"UR/OBC: ₹850 • SC/ST/PwBD: ₹175", qual:"Graduate",
      post:"Clerk", vacancy:"TBA",
      notif_url:"https://www.ibps.in", apply_url:"https://www.ibps.in",
      website:"https://www.ibps.in" },

    { id:"job-sbi-po-2025", title:"SBI PO 2025", org:"SBI Careers",
      start:"2025-09-XX", last:"2025-10-XX", fee:"UR/OBC: ₹750 • SC/ST/PwBD: ₹0", qual:"Graduate",
      post:"PO", vacancy:"TBA",
      notif_url:"https://sbi.co.in/web/careers", apply_url:"https://sbi.co.in/web/careers",
      website:"https://sbi.co.in" },

    { id:"job-sbi-clerk-2025", title:"SBI Clerk 2025", org:"SBI Careers",
      start:"2025-11-XX", last:"2025-12-XX", fee:"UR/OBC: ₹750 • SC/ST/PwBD: ₹0", qual:"Graduate",
      post:"Junior Associate", vacancy:"TBA",
      notif_url:"https://sbi.co.in/web/careers", apply_url:"https://sbi.co.in/web/careers",
      website:"https://sbi.co.in" },

    { id:"job-joinindianarmy-2025", title:"Indian Army Agniveer 2025", org:"Join Indian Army",
      start:"2025-02-XX", last:"2025-03-XX", fee:"As per rules", age:"17.5-21", qual:"10th/12th/ITI",
      post:"Agniveer", vacancy:"—",
      notif_url:"https://joinindianarmy.nic.in", apply_url:"https://joinindianarmy.nic.in",
      website:"https://joinindianarmy.nic.in" },

    { id:"job-joinindiannavy-2025", title:"Indian Navy SSR/MR 2025", org:"Join Indian Navy",
      start:"2025-04-XX", last:"2025-05-XX", fee:"As per rules", age:"As per notice", qual:"10th/12th",
      post:"SSR/MR", vacancy:"—",
      notif_url:"https://www.joinindiannavy.gov.in", apply_url:"https://www.joinindiannavy.gov.in",
      website:"https://www.joinindiannavy.gov.in" },

    { id:"job-airforce-agniveer-2025", title:"Indian Air Force Agniveer 2025", org:"IAF",
      start:"2025-01-XX", last:"2025-02-XX", fee:"As per rules", age:"17.5-21", qual:"10+2/3yr Diploma",
      post:"Agniveer Vayu", vacancy:"—",
      notif_url:"https://agnipathvayu.cdac.in", apply_url:"https://agnipathvayu.cdac.in",
      website:"https://indianairforce.nic.in" },

    { id:"job-bpsc-2025", title:"BPSC 70th Combined Competitive Exam", org:"BPSC",
      start:"2025-06-XX", last:"2025-07-XX", fee:"UR: ₹600 • Female/SC/ST/PWD: ₹150", age:"As per post", qual:"Graduate",
      post:"Various", vacancy:"TBA",
      notif_url:"https://www.bpsc.bih.nic.in/", apply_url:"https://onlinebpsc.bihar.gov.in/",
      website:"https://www.bpsc.bih.nic.in" },

    { id:"job-rpsc-2025", title:"RPSC Various Posts 2025", org:"RPSC",
      start:"2025-07-XX", last:"2025-08-XX", fee:"As per rules", age:"As per rules", qual:"As per post",
      post:"Various", vacancy:"TBA",
      notif_url:"https://rpsc.rajasthan.gov.in", apply_url:"https://rpsc.rajasthan.gov.in",
      website:"https://rpsc.rajasthan.gov.in" },

    { id:"job-mpsc-2025", title:"MPSC Group A/B 2025", org:"MPSC",
      start:"2025-06-XX", last:"2025-07-XX", fee:"As per rules", age:"As per rules", qual:"Graduate",
      post:"Group A/B", vacancy:"TBA",
      notif_url:"https://mpsc.gov.in", apply_url:"https://mpsc.gov.in",
      website:"https://mpsc.gov.in" },
  ],

  // ----------------- RESULTS (20) -----------------
  results: [
    { id:"res-ssc-cgl-2024-t1", title:"SSC CGL 2024 Tier-I Result", org:"SSC", date:"2025-08-20",
      result_url:"https://ssc.nic.in/Portal/Results", website:"https://ssc.nic.in", tag:"New" },
    { id:"res-ssc-chsl-2024", title:"SSC CHSL 2024 Result", org:"SSC", date:"2025-07-XX",
      result_url:"https://ssc.nic.in/Portal/Results", website:"https://ssc.nic.in" },
    { id:"res-ssc-gd-2024", title:"SSC GD Constable 2024 Result", org:"SSC",
      result_url:"https://ssc.nic.in/Portal/Results", website:"https://ssc.nic.in" },
    { id:"res-rrb-ntpc-2024", title:"RRB NTPC 2024 Result", org:"RRBs",
      result_url:"http://www.rrbcdg.gov.in/", website:"https://indianrailways.gov.in" },
    { id:"res-rrb-groupd-2024", title:"RRB Group D 2024 Result", org:"RRBs",
      result_url:"http://www.rrbcdg.gov.in/", website:"https://indianrailways.gov.in" },
    { id:"res-delhi-police-2024", title:"Delhi Police Constable 2024 Result", org:"Delhi Police/SSC",
      result_url:"https://delhipolice.gov.in", website:"https://delhipolice.gov.in" },
    { id:"res-ctet-2024", title:"CTET 2024 Result", org:"CBSE", 
      result_url:"https://ctet.nic.in", website:"https://ctet.nic.in" },
    { id:"res-nta-neet-ug-2024", title:"NTA NEET UG 2024 Result", org:"NTA",
      result_url:"https://neet.nta.nic.in", website:"https://nta.ac.in" },
    { id:"res-jee-main-2025-s1", title:"JEE Main 2025 Session 1 Result", org:"NTA",
      result_url:"https://jeemain.nta.ac.in", website:"https://nta.ac.in" },
    { id:"res-cuet-ug-2025", title:"CUET UG 2025 Result", org:"NTA",
      result_url:"https://cuet.samarth.ac.in", website:"https://nta.ac.in" },
    { id:"res-upsc-pre-2025", title:"UPSC Civil Services (Pre) 2025 Result", org:"UPSC",
      result_url:"https://upsc.gov.in", website:"https://upsc.gov.in" },
    { id:"res-ibps-po-2024", title:"IBPS PO 2024 Result", org:"IBPS",
      result_url:"https://www.ibps.in", website:"https://www.ibps.in" },
    { id:"res-ibps-clerk-2024", title:"IBPS Clerk 2024 Result", org:"IBPS",
      result_url:"https://www.ibps.in", website:"https://www.ibps.in" },
    { id:"res-sbi-po-2024", title:"SBI PO 2024 Final Result", org:"SBI",
      result_url:"https://sbi.co.in/web/careers", website:"https://sbi.co.in" },
    { id:"res-sbi-clerk-2024", title:"SBI Clerk 2024 Final Result", org:"SBI",
      result_url:"https://sbi.co.in/web/careers", website:"https://sbi.co.in" },
    { id:"res-upsssc-pet-2024", title:"UPSSSC PET 2024 Result", org:"UPSSSC",
      result_url:"http://upsssc.gov.in", website:"http://upsssc.gov.in" },
    { id:"res-bpsc-69-2024", title:"BPSC 69th Result", org:"BPSC",
      result_url:"https://www.bpsc.bih.nic.in/", website:"https://www.bpsc.bih.nic.in" },
    { id:"res-rpsc-2024", title:"RPSC Various 2024 Results", org:"RPSC",
      result_url:"https://rpsc.rajasthan.gov.in/results", website:"https://rpsc.rajasthan.gov.in" },
    { id:"res-mpsc-2024", title:"MPSC 2024 Results", org:"MPSC",
      result_url:"https://mpsc.gov.in/Results", website:"https://mpsc.gov.in" },
    { id:"res-ssc-jht-2024", title:"SSC JHT 2024 Result", org:"SSC",
      result_url:"https://ssc.nic.in/Portal/Results", website:"https://ssc.nic.in" },
  ],

  // ----------------- ADMIT CARDS (20) -----------------
  admit: [
    { id:"adm-ssc-cgl-2025-t2", title:"SSC CGL 2025 Tier-II Admit Card", org:"SSC",
      admit_url:"https://ssc.nic.in/Portal/AdmitCard", website:"https://ssc.nic.in", tag:"New" },
    { id:"adm-ssc-chsl-2025", title:"SSC CHSL 2025 Admit Card", org:"SSC",
      admit_url:"https://ssc.nic.in/Portal/AdmitCard", website:"https://ssc.nic.in" },
    { id:"adm-ssc-gd-2025", title:"SSC GD Constable 2025 Admit Card", org:"SSC",
      admit_url:"https://ssc.nic.in/Portal/AdmitCard", website:"https://ssc.nic.in" },
    { id:"adm-rrb-alp-2025", title:"RRB ALP 2025 Admit Card", org:"RRBs",
      admit_url:"http://www.rrbcdg.gov.in/", website:"https://indianrailways.gov.in" },
    { id:"adm-rrb-ntpc-2025", title:"RRB NTPC 2025 Admit Card", org:"RRBs",
      admit_url:"http://www.rrbcdg.gov.in/", website:"https://indianrailways.gov.in" },
    { id:"adm-delhi-police-2025", title:"Delhi Police Constable 2025 Admit Card", org:"Delhi Police/SSC",
      admit_url:"https://delhipolice.gov.in", website:"https://delhipolice.gov.in" },
    { id:"adm-ctet-jan-2025", title:"CTET January 2025 Admit Card", org:"CBSE",
      admit_url:"https://ctet.nic.in", website:"https://ctet.nic.in" },
    { id:"adm-jee-main-2025-s1", title:"JEE Main 2025 Session 1 Admit Card", org:"NTA",
      admit_url:"https://jeemain.nta.ac.in", website:"https://nta.ac.in" },
    { id:"adm-neet-ug-2025", title:"NEET UG 2025 Admit Card", org:"NTA",
      admit_url:"https://neet.nta.nic.in", website:"https://nta.ac.in" },
    { id:"adm-cuet-ug-2025", title:"CUET UG 2025 Admit Card", org:"NTA",
      admit_url:"https://cuet.samarth.ac.in", website:"https://nta.ac.in" },
    { id:"adm-upsc-pre-2025", title:"UPSC Civil Services (Pre) 2025 Admit Card", org:"UPSC",
      admit_url:"https://upsconline.nic.in/eadmitcard", website:"https://upsc.gov.in" },
    { id:"adm-ibps-po-2025", title:"IBPS PO 2025 Admit Card", org:"IBPS",
      admit_url:"https://www.ibps.in", website:"https://www.ibps.in" },
    { id:"adm-ibps-clerk-2025", title:"IBPS Clerk 2025 Admit Card", org:"IBPS",
      admit_url:"https://www.ibps.in", website:"https://www.ibps.in" },
    { id:"adm-sbi-po-2025", title:"SBI PO 2025 Admit Card", org:"SBI",
      admit_url:"https://sbi.co.in/web/careers", website:"https://sbi.co.in" },
    { id:"adm-sbi-clerk-2025", title:"SBI Clerk 2025 Admit Card", org:"SBI",
      admit_url:"https://sbi.co.in/web/careers", website:"https://sbi.co.in" },
    { id:"adm-upsssc-pet-2025", title:"UPSSSC PET 2025 Admit Card", org:"UPSSSC",
      admit_url:"http://upsssc.gov.in", website:"http://upsssc.gov.in" },
    { id:"adm-bpsc-2025", title:"BPSC 70th Admit Card", org:"BPSC",
      admit_url:"https://www.bpsc.bih.nic.in/", website:"https://www.bpsc.bih.nic.in" },
    { id:"adm-rpsc-2025", title:"RPSC Admit Card 2025", org:"RPSC",
      admit_url:"https://rpsc.rajasthan.gov.in/admitCard", website:"https://rpsc.rajasthan.gov.in" },
    { id:"adm-mpsc-2025", title:"MPSC Admit Card 2025", org:"MPSC",
      admit_url:"https://mpsc.gov.in/AdmitCard", website:"https://mpsc.gov.in" },
    { id:"adm-ssc-jht-2025", title:"SSC JHT 2025 Admit Card", org:"SSC",
      admit_url:"https://ssc.nic.in/Portal/AdmitCard", website:"https://ssc.nic.in" },
  ],

  // ----------------- SCHEMES (10 – extendable to 20) -----------------
  schemes: [
    { id:"sch-pmkisan", title:"PM-KISAN eKYC / Beneficiary Status", org:"PM-KISAN", website:"https://pmkisan.gov.in", notif_url:"https://pmkisan.gov.in" },
    { id:"sch-eshram", title:"e-Shram Card Registration / Update", org:"Ministry of Labour", website:"https://eshram.gov.in", notif_url:"https://eshram.gov.in" },
    { id:"sch-abha", title:"ABHA (Health ID) Create / Link", org:"NHS / ABDM", website:"https://abha.abdm.gov.in", notif_url:"https://abdm.gov.in" },
    { id:"sch-ayushman", title:"Ayushman Bharat (PM-JAY) Card", org:"NHA", website:"https://pmjay.gov.in", notif_url:"https://pmjay.gov.in" },
    { id:"sch-pmays", title:"PM Awas Yojana (PMAY-Urban)", org:"MoHUA", website:"https://pmay-urban.gov.in", notif_url:"https://pmay-urban.gov.in" },
    { id:"sch-pmjay-secc", title:"Ayushman Eligibility (SECC)", org:"NHA", website:"https://mera.pmjay.gov.in", notif_url:"https://pmjay.gov.in" },
    { id:"sch-kisan-credit", title:"Kisan Credit Card (KCC)", org:"GoI", website:"https://agricoop.nic.in", notif_url:"https://agricoop.nic.in" },
    { id:"sch-nps", title:"NPS Registration/Status", org:"PFRDA", website:"https://enps.nsdl.com", notif_url:"https://pfrda.org.in" },
    { id:"sch-sukanya", title:"Sukanya Samriddhi Yojana", org:"India Post/Bank", website:"https://www.indiapost.gov.in", notif_url:"https://www.rbi.org.in" },
    { id:"sch-lpg-subsidy", title:"LPG Subsidy / PAHAL", org:"MoPNG", website:"https://mylpg.in", notif_url:"https://www.mylpg.in" },
  ],

  // ----------------- DAILY (10 – extendable to 20) -----------------
  daily: [
    { id:"dl-aadhaar-update", title:"Aadhaar Update / PVC", org:"UIDAI", website:"https://myaadhaar.uidai.gov.in", notif_url:"https://uidai.gov.in" },
    { id:"dl-pan-services", title:"PAN Apply / Update", org:"NSDL e-Gov", website:"https://www.onlineservices.nsdl.com/paam/endUserRegisterContact.html", notif_url:"https://www.incometax.gov.in" },
    { id:"dl-pan-uti", title:"PAN Services (UTIITSL)", org:"UTIITSL", website:"https://www.pan.utiitsl.com", notif_url:"https://utiitsl.com" },
    { id:"dl-digilocker", title:"DigiLocker Login", org:"MeitY", website:"https://digilocker.gov.in", notif_url:"https://digilocker.gov.in" },
    { id:"dl-fastag-kyc", title:"FASTag KYC Update", org:"NHAI", website:"https://fastag.ihmcl.com", notif_url:"https://ihmcl.co.in" },
    { id:"dl-epfo-passbook", title:"EPFO Passbook", org:"EPFO", website:"https://passbook.epfindia.gov.in", notif_url:"https://www.epfindia.gov.in" },
    { id:"dl-esic", title:"ESIC Services", org:"ESIC", website:"https://www.esic.gov.in", notif_url:"https://www.esic.gov.in" },
    { id:"dl-pf-uan", title:"UAN Services", org:"EPFO", website:"https://unifiedportal-mem.epfindia.gov.in/memberinterface/", notif_url:"https://www.epfindia.gov.in" },
    { id:"dl-voter", title:"Voter Services (NVSP)", org:"ECI", website:"https://voters.eci.gov.in", notif_url:"https://eci.gov.in" },
    { id:"dl-passport", title:"Passport Seva", org:"MEA", website:"https://www.passportindia.gov.in", notif_url:"https://www.passportindia.gov.in" },
  ],

  // ----------------- DOCUMENTS (10 – extendable to 20) -----------------
  docs: [
    { id:"doc-income-cert", title:"Income Certificate (State Portals)", org:"State eDistrict", website:"https://services.india.gov.in" },
    { id:"doc-caste-cert", title:"Caste Certificate (State Portals)", org:"State eDistrict", website:"https://services.india.gov.in" },
    { id:"doc-residence-cert", title:"Residence/Domicile Certificate", org:"State eDistrict", website:"https://services.india.gov.in" },
    { id:"doc-birth-cert", title:"Birth Certificate", org:"Civil Registration", website:"https://crsorgi.gov.in" },
    { id:"doc-marriage-cert", title:"Marriage Certificate", org:"State/ULB", website:"https://services.india.gov.in" },
    { id:"doc-rc-dl", title:"RC / DL Services (Parivahan)", org:"MoRTH", website:"https://parivahan.gov.in" },
    { id:"doc-abc-id", title:"ABC ID (Academic Bank of Credits)", org:"MoE", website:"https://www.abc.gov.in", notif_url:"https://www.abc.gov.in" },
    { id:"doc-scholarship", title:"National Scholarship Portal", org:"NSP", website:"https://scholarships.gov.in" },
    { id:"doc-ration", title:"Ration Card (State Portals)", org:"State Civil Supplies", website:"https://services.india.gov.in" },
    { id:"doc-rtps", title:"RTPS / eDistrict Services", org:"State Portals", website:"https://services.india.gov.in" },
  ],
};
</script>
